from .settings import settings
from .prompts import (
    JUNIT_GENERATOR_SYSTEM,
    JUNIT_GENERATOR_PROMPT,
    JUNIT_GENERATOR_FINETUNE_COVERAGE,
    JUNIT_GENERATOR_FINETUNE_FAILURES,
    JUNIT_VALIDATOR_SYSTEM,
    JUNIT_VALIDATOR_PROMPT,
    COMPILATION_FIX_SYSTEM,
    COMPILATION_FIX_PROMPT,
    JACOCO_ANALYSIS_SYSTEM,
    JACOCO_ANALYSIS_PROMPT,
    EXECUTOR_ANALYSIS_SYSTEM,
    EXECUTOR_ANALYSIS_PROMPT,
)
